name: impacts
channels:
  - defaults
dependencies:
  - python
  - numpy
  - xarray
  - pandas
  - matplotlib
  - cartopy
  - arm_pyart
  - metpy
  - notebook
  - datetime
  - boto
  - geopy
  - h5py
  - scipy
  - dask
  - netcdf4
  - h5netcdf
  - pylint
  - pyproj
